# Site settings
title: Corporate Accelerator DB
subtitle: the best overview of all corporate acceleration programs
email: hello@florianheinemann.com
description: > # this means to ignore newlines until "baseurl:"
  A regularly maintained list of Corporate Accelerator 
  programs across the world
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.corporate-accelerators.net" # the base hostname & protocol for your site
twitter_username: thesumofall
github_username:  florianheinemann
exclude: [Readme.md]

# Build settings
markdown: kramdown
highlighter: rouge